# Generated by Django 3.1.1 on 2020-09-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='Staff_number',
            new_name='staff_number',
        ),
        migrations.AlterField(
            model_name='admin',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
