# Generated by Django 3.1.1 on 2020-09-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0002_auto_20200924_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_title',
        ),
        migrations.AddField(
            model_name='course',
            name='course_title',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='student',
            name='matric_number',
        ),
        migrations.AddField(
            model_name='student',
            name='matric_number',
            field=models.ManyToManyField(to='faceapp.Course'),
        ),
    ]
