# Generated by Django 3.1.1 on 2020-09-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0003_auto_20200925_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_title',
        ),
        migrations.AddField(
            model_name='course',
            name='course_title',
            field=models.ManyToManyField(to='faceapp.Student'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='matric_number',
        ),
        migrations.AddField(
            model_name='student',
            name='matric_number',
            field=models.CharField(default=7876, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
