# Generated by Django 3.1.1 on 2020-09-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0006_auto_20200925_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
