# Generated by Django 3.1.1 on 2020-09-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0008_auto_20200925_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student_matric_number',
        ),
        migrations.AddField(
            model_name='course',
            name='student_matric_number',
            field=models.ManyToManyField(null=True, to='faceapp.Student'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='matric_number',
        ),
        migrations.AddField(
            model_name='student',
            name='matric_number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
