# Generated by Django 3.1.1 on 2020-09-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0009_auto_20200925_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student_matric_number',
            field=models.ManyToManyField(to='faceapp.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='matric_number',
            field=models.CharField(default=7680, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
