# Generated by Django 3.1.1 on 2020-09-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0010_auto_20200925_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student_matric_number',
            field=models.ManyToManyField(null=True, to='faceapp.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='matric_number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
