# Generated by Django 3.1.1 on 2020-09-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0011_auto_20200925_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student_matric_number',
            field=models.ManyToManyField(to='faceapp.Student'),
        ),
    ]
