# Generated by Django 3.1.1 on 2020-10-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0012_auto_20200925_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='course',
            name='student_matric_number',
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='', max_length=6, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='courses_registered',
            field=models.ManyToManyField(to='faceapp.Course'),
        ),
    ]
