# Generated by Django 3.1.1 on 2020-10-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0013_auto_20201001_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
